;/*FB_PKG_DELIM*/

__d("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group",selections:[{alias:"off_plat_comet_crawlability_gk",args:[{kind:"Literal",name:"gk_name",value:"groups_off_platform_distribution_comet_crawability"}],concreteType:"EntGKCheck",kind:"LinkedField",name:"gk_check",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"passes_gk",storageKey:null}],storageKey:'gk_check(gk_name:"groups_off_platform_distribution_comet_crawability")'}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("GroupsCometEndOfFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6001775859842406"}),null);
__d("GroupsCometEndOfFeedQuery$Parameters",["GroupsCometEndOfFeedQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometEndOfFeedQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometEndOfFeedQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupRoomCreateAudioChannelDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5790704310990324"}),null);
__d("GroupRoomCreateAudioChannelDialogRootQuery$Parameters",["GroupRoomCreateAudioChannelDialogRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupRoomCreateAudioChannelDialogRootQuery_facebookRelayOperation"),metadata:{},name:"GroupRoomCreateAudioChannelDialogRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("useGroupRoomCreateAudioChannelDialog_group.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useGroupRoomCreateAudioChannelDialog_group",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"Group",abstractKey:null};e.exports=a}),null);
__d("addLocalGroupFeedInlineMessage",["CometRelay","cometUniqueID","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";function h(a,b,d){a=a.get(b);if(a==null){c("recoverableViolation")("Group Feed Inline Message Updater: Could not find group edge in store","groups_comet");return}b=a.getLinkedRecords("local_feed_inline_messages")||[];a.setLinkedRecords([].concat(b,[d]),"local_feed_inline_messages")}function a(a,b,e){d("CometRelay").commitLocalUpdate(a,function(a){var d="client:LocalGroupFeedVideoInlineMessage:"+c("cometUniqueID")(),f=a.create(d,"LocalGroupFeedVideoInlineMessage");f.setValue(String(d),"id");f.setValue(String(b),"group_id");f.setValue(String(e),"message");h(a,b,f)})}function b(a,b,e){d("CometRelay").commitLocalUpdate(a,function(a){var d=a.get(b);if(d==null){c("recoverableViolation")("Group Feed Inline Message Updater: Could not find group edge in store","groups_comet");return}var f=d.getLinkedRecords("local_feed_inline_messages")||[];f=f.filter(function(a){return(a==null?void 0:a.getDataID())!==e});a["delete"](e);d.setLinkedRecords(f,"local_feed_inline_messages")})}g.addLocalVideoFeedMessage=a;g.removeLocalFeedMessage=b}),98);
__d("GroupsCometLightweightGroupOptimisticPostContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({optimisticPostDisposables:[],setOptimisticPostDisposables:function(){}});g["default"]=b}),98);
__d("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList.react",["CometFeedInfiniteScrollSuspenseList.react","CometRelay","GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql","gkx","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react"),j=d("react").useMemo;function a(a){var e=a.group$key,f=babelHelpers.objectWithoutPropertiesLoose(a,["group$key"]);a=d("CometRelay").useFragment(h!==void 0?h:h=b("GroupsCometFeedCrawlerOptimizedInfiniteScrollSuspenseList_group.graphql"),e);var g=(a=a==null?void 0:(e=a.off_plat_comet_crawlability_gk)==null?void 0:e.passes_gk)!=null?a:!1;e=j(function(){return!c("gkx")("1779508")||!g?f:babelHelpers["extends"]({},f,{incrementalRendering:!1,waitOnScrollIntent:!1})},[g,f]);return i.jsx(c("CometFeedInfiniteScrollSuspenseList.react"),babelHelpers["extends"]({},e))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometFeedRegularStoriesGlimmer.react",["BaseGlimmer.react","CometFeedStoryGlimmer.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={header:{paddingBottom:"x1l90r2v",paddingStart:"x1swvt13",paddingTop:"x1cnzs8",$$css:!0},headerGlimmer:{borderTopStartRadius:"x8u2fvd",borderTopEndRadius:"x1ht7hnu",borderBottomEndRadius:"x1quq95r",borderBottomStartRadius:"x5yzy4c",height:"x170jfvy",marginTop:"xr1yuqi",width:"x1lzt3e6",$$css:!0}};function a(a){a=a.hasSortingSetting;a=a===void 0?!1:a;return h.jsxs(h.Fragment,{children:[h.jsx("div",{className:"x1l90r2v x1swvt13 x1cnzs8",children:h.jsx(c("BaseGlimmer.react"),{index:0,xstyle:i.headerGlimmer})}),h.jsx(c("CometFeedStoryGlimmer.react"),{}),h.jsx(c("CometFeedStoryGlimmer.react"),{}),a&&h.jsxs(h.Fragment,{children:[h.jsx(c("CometFeedStoryGlimmer.react"),{}),h.jsx(c("CometFeedStoryGlimmer.react"),{})]})]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("GroupsCometEndOfFeed.entrypoint",["GroupsCometEndOfFeedQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.id;return{queries:{endOfFeedQueryReference:{options:{fetchPolicy:"network-only"},parameters:c("GroupsCometEndOfFeedQuery$Parameters"),variables:{id:a,scale:1}}}}},root:c("JSResourceForInteraction")("GroupsCometEndOfFeed.react").__setRef("GroupsCometEndOfFeed.entrypoint")};b=a;g["default"]=b}),98);
__d("GroupRoomCreateAudioChannelDialog.entrypoint",["GroupRoomCreateAudioChannelDialogRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.groupID;return{queries:{queryReference:{parameters:b("GroupRoomCreateAudioChannelDialogRootQuery$Parameters"),variables:{groupID:a,scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("GroupRoomCreateAudioChannelDialog.react").__setRef("GroupRoomCreateAudioChannelDialog.entrypoint")};g["default"]=a}),98);
__d("useGroupRoomCreateAudioChannelDialog",["GroupRoomCreateAudioChannelDialog.entrypoint","useCometEntryPointDialog","useGroupRoomCreateAudioChannelDialog_group.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;h!==void 0?h:h=b("useGroupRoomCreateAudioChannelDialog_group.graphql");function a(a,b){a=c("useCometEntryPointDialog")(c("GroupRoomCreateAudioChannelDialog.entrypoint"),{groupID:a},"button");var d=a[0];return function(a){return d({loggingData:b},a)}}g["default"]=a}),98);
__d("mapMap",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=new Map();a.forEach(function(a,d){c.set(d,b(a,d))});return c}f["default"]=a}),66);
__d("GroupsMallUserViewedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1835973");c=b("FalcoLoggerInternal").create("groups_mall_user_viewed",a);e.exports=c}),null);
__d("GroupsCometNewMemberGreetingDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5674093209376826"}),null);
__d("mapMapToArray",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){var c=[],d=0;for(var e=a,f=Array.isArray(e),g=0,e=f?e:e[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var h;if(f){if(g>=e.length)break;h=e[g++]}else{g=e.next();if(g.done)break;h=g.value}h=h;var i=h[0];h=h[1];c.push(b(h,i,d,a));d++}return c}f["default"]=a}),66);